# Dependencies
markdown: kramdown
highlighter: rouge

plugins:
    - jekyll-sitemap

# File rules
exclude: [vendor, Dangerfile, Gemfile, Gemfile.lock, LICENSE, README.md, CODE_OF_CONDUCT.md, CONTRIBUTING.md, new_draft.sh, github_issue_generator.rb]

# Permalinks
permalink: /:title/

# Site
title: 'Swift Weekly Brief'
description: 'A community-driven weekly newsletter about Swift.org'
url: https://swiftweekly.github.io
logo: /img/logo.png
timezone: America/Los_Angeles

repo_name: swiftweekly.github.io

twitter:
    username: swiftlybrief

# Setup
excerpt_separator: <!--excerpt-->

# Data
links:
    rss: '/feed.xml'
    twitter: 'https://twitter.com/swiftlybrief'
    github: 'https://github.com/SwiftWeekly/swiftweekly.github.io'
    issue: 'https://github.com/SwiftWeekly/swiftweekly.github.io/issues/new'
    pull: 'https://github.com/SwiftWeekly/swiftweekly.github.io/compare'
    applenews: 'https://apple.news/TIlGIYluMTGWA-CIToVtF4Q'
